

export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  RESET_PRODUCT_DATA: "RESET_PRODUCT_DATA",
  //все заказы
  SET_ORDERS: "SET_ORDERS",
  //корзина
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SET_CART: "SET_CART_DATA",
  CLEAR_CART: "CLEAR_CART",

  //избранное
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
  SET_FAVORITES: "SET_FAVORITES",
  CLEAR_FAVORITES: "CLEAR_FAVORITES",
  LOAD_FAVORITES: 'LOAD_FAVORITES'
};
