

export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  RESET_PRODUCT_DATA: "RESET_PRODUCT_DATA",
};
