

export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  RESET_PRODUCT_DATA: "RESET_PRODUCT_DATA",
  SET_ORDERS: "SET_ORDERS",
  SET_CART: "SET_CART_DATA",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART"
};
