export * from "./AdminPage/AdminPage"
export * from "./CartPage/CartPage"
export * from "./CatalogPage/CatalogPage"
export * from "./HomePage/HomePage"
export * from "./PersonalPage/PersonalPage"
export * from "./ProductCardPage/ProductCardPage"
export * from "./authorization/Authorization"

export * from "./registration/Registration"
export * from "./FavoriesPage/FaforitesPage"
