export const transformProduct = (dbProduct) => ({
  id: dbProduct.id,
  imgUrl: dbProduct.img_url,
  category: dbProduct.category,
  price: dbProduct.price,
  title: dbProduct.title,
  form: dbProduct.form,
  width: dbProduct.width,
  height: dbProduct.height,
  length: dbProduct.length,
  color: dbProduct.color,
  desc: dbProduct.desc,
  content: dbProduct.content,
  publishedAt: dbProduct.published_at,
});
